---
- name: Starting MongoDB
  become: "{{ ansible_connection is defined }}"
  community.docker.docker_container:
    name: mongo
    image: '{{ mongo_docker_image }}:{{ mongo_docker_tag }}'
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ mongo_port }}:27017'
    volumes:
      - '{{ prefix }}/mongodb:/data/db'
    container_default_behavior: no_defaults
  notify:
    - Waiting MongoDB
  when:
    - mongo_deploy
- name: Starting TestAPI
  become: "{{ ansible_connection is defined }}"
  community.docker.docker_container:
    name: testapi
    image: '{{ testapi_docker_image }}:{{ testapi_docker_tag }}'
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ testapi_port }}:8000'
    env:
      base_url: '{{ testapi_base_url }}'
      mongodb_url: '{{ mongo_url }}'
      auth: 'false'
    container_default_behavior: no_defaults
  notify:
    - Waiting TestAPI
- name: Flushing handlers
  meta: flush_handlers
