---
- name: Waiting TestAPI
  uri:
    url: "{{ testapi_url }}/results"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((testapi_wait |int) / 5) |int }}"
  delay: 5
- name: Waiting MongoDB
  pause:
    seconds: '{{ mongo_wait }}'
